#Playbook to add line to a file if the file does not exists.
---
- hosts: centos
  tasks:
    - name: Create /lab directory
      become: yes
      file:
        path: /lab
        state: directory
        mode: 0755
    - name: Update application.conf
      become: yes
      lineinfile:
        path: /lab/application.conf
        line: state=start
        create: yes

